# Headshot players with arrows if shot from far enough away.
# Copyright (C) 2013 Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# 
# 
# auto-update-download: Whether or not to automatically download new updates
# distance:
#   enabled: Whether or not damage accumulation based on distance is enabled
#   considered-headshot: Whether or not damage accumulation is considered a headshot
#                        when it's above 'headshot-damage'
#   min-distance: The minimum distance the arrow must travel before it starts
#                 accumulating extra damage
#   extra-damage-per-block: How much extra damage is added to the arrow per block
#                           after it travels 'min-distance'
#   headshot-damage: The minimum total damage (regular + extra) for a hit to be
#                    classified as a headshot (if 'considered-headshot' is true)
# hitboxes:
#   enabled: Whether or not damage multipliers based on hitboxes are enabled
#   [body part]:
#     multiplier: The damage multiplier for this body part
# strings: Messages sent to the player
#   headshot-shooter: The message to be sent to the shooter if they headshot a player
#                     ('%s' is replaced by the target player's name)
#   headshot-player: The message to be sent to the player if they are headshotted
#                    ('%s' is replaced by the shooter's name)
#   headshot-death-message: The replacement for the default death message when a
#                           a player headshots another
#                           (The first '%s' is replaced by the target player's name,
#                           the second '%s' is replaced by the shooter's name, and
#                           the third '%s' is replaced by the distance the
#                           arrow travelled)

auto-update-download: true
distance:
  enabled: true
  considered-headshot: true
  min-distance: 10.0
  extra-damage-per-block: 1.5
  headshot-damage: 20.0
hitboxes:
  enabled: true
  head:
    multiplier: 2.0
  torso:
    multiplier: 1.0
  legs:
    multiplier: 0.7
strings:
  headshot-shooter: '&eYou have headshotted %s!'
  headshot-player: '&cYou have been headshotted by %s!'
  headshot-death-message: '&b%s was headshotted by %s from %sm away'
