# Headshot players with arrows if shot from far enough away.
# Copyright (C) 2013 Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# 
# 
# auto-update-notify: Whether or not to automatically notify admins of new updates
# distance:
#   enabled: Whether or not damage accumulation based on distance is enabled
#   considered-headshot: Whether or not damage accumulation is considered a headshot
#                        when it's above 'headshot-damage'
#   min-distance: The minimum distance the arrow must travel before it starts
#                 accumulating extra damage
#   extra-damage-per-block: How much extra damage is added to the arrow per block
#                           after it travels 'min-distance'
#   headshot-damage: The minimum total damage (regular + extra) for a hit to be
#                    classified as a headshot (if 'considered-headshot' is true)
# hitboxes:
#   enabled: Whether or not damage multipliers based on hitboxes are enabled
#   [body part]:
#     above/below: The relative Y distance away from the player's feet the arrow
#                  has to hit above/below to count as a hit for this body part.
#                  Raise or lower this, respectively, to have a smaller target
#     multiplier: The damage multiplier for this body part
#     effects: A list of effects to be applied when this body part is hit
#              Syntax: Probability:Type:Type_Options
#                Probability is a number from 1–100
#                Type is one of the following, listed alongside its options:
#                  PotionEffect:
#                    Options: Name:Duration(in ticks, 1/20th of a second):Amplifier
#                    (Potion names: SPEED, SLOW, FAST_DIGGING, SLOW_DIGGING,
#                     INCREASE_DAMAGE, HEAL, HARM, JUMP, CONFUSION, REGENERATION,
#                     DAMAGE_RESISTANCE, FIRE_RESISTANCE, WATER_BREATHING, INVISIBILITY,
#                     BLINDNESS, NIGHT_VISION, HUNGER, WEAKNESS, POISON, WITHER,
#                     HEALTH_BOOST, ABSORPTION, SATURATION)
#              Example:
#                effects: ['50:PotionEffect:HEAL:30:1']
#                A healing potion effect with a 50% change to affect the player,
#                lasting 1.5 seconds with an amplifier of 1
# armour-damage-divisor:
#   [item]: What to divide the total damage by for this item if hit in the hitbox which
#           this item is worn in
# strings: Messages sent to the player
#   headshot-shooter: The message to be sent to the shooter if they headshot a player
#                     ('%s' is replaced by the target player's name)
#   headshot-player: The message to be sent to the player if they are headshotted
#                    ('%s' is replaced by the shooter's name)
#   headshot-death-message: The replacement for the default death message when a
#                           a player headshots another
#                           (The first '%s' is replaced by the target player's name,
#                           the second '%s' is replaced by the shooter's name, and
#                           the third '%s' is replaced by the distance the
#                           arrow travelled)

auto-update-notify: true
distance:
  enabled: true
  considered-headshot: true
  min-distance: 10.0
  extra-damage-per-block: 1.5
  headshot-damage: 20.0
hitboxes:
  enabled: true
  head:
    above: 1.5
    multiplier: 2.0
    effects: []
  torso:
    multiplier: 1.0
    effects:
    - 10:PotionEffect:WITHER:30:0
  legs:
    below: 0.8
    multiplier: 0.7
    effects:
    - 75:PotionEffect:SLOW:20:0
  feet:
    below: 0.4
    multiplier: 0.5
    effects:
      - 75:PotionEffect:SLOW:30:0
armour-damage-divisor:
  LEATHER_HELMET: 1.1
  LEATHER_CHESPLATE: 1.1
  LEATHER_LEGGINGS: 1.1
  LEATHER_BOOTS: 1.1
  GOLD_HELMET: 1.15
  GOLD_CHESPLATE: 1.15
  GOLD_LEGGINGS: 1.15
  GOLD_BOOTS: 1.15
  CHAINMAIL_HELMET: 1.25
  CHAINMAIL_CHESPLATE: 1.25
  CHAINMAIL_LEGGINGS: 1.25
  CHAINMAIL_BOOTS: 1.25
  IRON_HELMET: 1.3
  IRON_CHESPLATE: 1.3
  IRON_LEGGINGS: 1.3
  IRON_BOOTS: 1.3
  DIAMOND_HELMET: 1.5
  DIAMOND_CHESPLATE: 1.5
  DIAMOND_LEGGINGS: 1.5
  DIAMOND_BOOTS: 1.5
strings:
  headshot-shooter: '&eYou have headshotted %s!'
  headshot-player: '&cYou have been headshotted by %s!'
  headshot-death-message: '&b%s was headshotted by %s from %sm away'
