# Headshot players with arrows if shot from far enough away.
# Copyright (C) 2013 Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

name: Headshot
main: me.hoot215.headshot.Headshot
version: 1.2
author: Hoot215
permissions:
  headshot:
    description: 'Allows players to headshot other players'
    default: true
